services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET: ${SECRET}
    # Remove port mapping - only accessible through nginx
    volumes:
      - ./backend/app:/app/app

  frontend:
    build: ./frontend
    restart: unless-stopped
    # Remove port mapping - only accessible through nginx
    environment:
      VITE_API_URL: ${VITE_API_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent host node_modules from overriding container node_modules

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
