services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET: ${SECRET}
    ports:
      - '8000:8000'
    volumes:
      - ./backend/app:/app/app

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - '5173:5173'
    environment:
      VITE_API_URL: ${VITE_API_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent host node_modules from overriding container node_modules
