services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/appdb
      SECRET: supersecretchangeme
    ports:
      - '8000:8000'
    volumes:
      - ./backend/app:/app/app

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - '5173:5173'
    environment:
      VITE_API_URL: http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent host node_modules from overriding container node_modules
